#defines the database service
db:
  #uses a postgres database
  image: postgres
#defines the web application services
web:
  #specifies the build path
  build: .
  #specifies the command to start the rails server on local host port 3000
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #the web application
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  #links the database service to this web application services
  #there are two containers (one for the web app and one for the database)
  #this link ensures the two are connected and belong to the same application
  links:
    - db
